config/routes.rb
Rails.application.routes.draw do

  mount Api::ApplicationApi => '/api'
  root 'topics#index'

  resources :topics do
    collection do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include TopicsHelper
  def index
    @q = Topic.search(params[:q])
    if params[:q] &&  params[:q].values.first == ENV['SCRIPT_BLOG_ACCESS']
      @topics = Topic.where("hidden is true").order(created_at: :desc).page(params[:page]).page(params[:page]).per(20)
    else
      @topics = @q.result(distinct: true).where("hidden is not true").order(created_at: :desc).page(params[:page]).per(20)
    end
  end

  def show
    @topic = Topic.friendly.find(params[:id])
    @topic.update(reading_count: @topic.reading_count + 1)
    @q = Topic.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def get_tags(tags)
    return [] if tags.nil? || tags.length == 0
    return tags.split(/,/)
  end
end

app/views/layouts/_footer.html.erb
<footer class="author">
  <!-- <hr> -->
  <div class="footer">
    <span class="text-muted" title="dccmmtop@gmail.com">梦里不知身是客</span> 
    <i class="fa fa-heart love"></i>
    <a href="http://www.cnblogs.com/cmmdc/" target="_blank" class="girl-friend text-muted"> 一晌贪欢</a>
    </br>
    <span><%= (Date.today - Date.parse('2016-4-4')).to_i %></span>
  </div>
</footer>

app/views/layouts/_search.html.erb
<div class="pull-right search">
  <%= search_form_for @q,url: topics_path,html:{class: 'form-inline'} do |f| %>
    <%= f.search_field :title_or_body_or_tags_cont ,class: 'form-control'%>
    <%= f.submit :class => "btn btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>梦里不知身是客</title>
    <!-- <meta http&#45;equiv="refresh" content="0;url=https://dccmm.world/"> -->
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" type="image/png" href="<%= asset_path("favicon.png") %>"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-1758385820416376",
        enable_page_level_ads: true
      });
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120063959-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-120063959-1');
    </script>
  </head>

  <body>
    <div class="masthead">
      <div class="container">
        <h3 class="masthead-title">
          <a href="/" title="Home">梦里不知身是客</a>
          <small>My little tech blog</small>
          <div id="search">
            <%= search_form_for @q,url: topics_path,html:{} do |f| %>
              <%= f.search_field :title_or_body_or_tags_cont , id: "search-query",placeholder: "Search" %>
            <% end %>
          </div>
        </h3>
      </div>
    </div>
    <div class="container main-content">
      <%= yield %>
    </div>
    <%= render "/layouts/footer.html.erb" %>
  </body>
</html>

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <div class="index-title"><%= link_to topic.title,topic_path(topic) %></div>
  <span class="info"><%= topic.created_at.strftime("%Y-%m-%d")  %></span>
  <!-- <span class="info">阅读<%= topic.reading_count  %>次</span> -->
  <br></br>
<% end %>
<div class="text-center">
  <%= paginate @topics %>
</div>

app/views/topics/search.html.erb
<% if @topics.size == 0 %>
  <h1 class="center-block alert-message">Not Found...</h1>
<% else %>
  <p hidden data-search=<%= params[:search] %>></p>
  <div class="search-result">
    <% @topics.each do |topic| %>
      <h4 class="index-title"><%= link_to topic.title,topic_path(topic) %></h4>
      <span class="info"><%= topic.created_at.strftime("%Y-%m-%d")  %></span>  •
      <span class="info">阅读<%= topic.reading_count  %>次</span>
      <br></br>
    <% end %>
  </div>
<% end %>

app/views/topics/show.html.erb
<h1 class="center-block"><%= @topic.title %></h1>
<hr>
<div class="sub-title">
  <%# <%= link_to root_path do %>
  <%#   <%= icon("fas","home",{class: 'fa-fw'}) %>
  <%# <% end %> 
<span class="info"><%= @topic.created_at.strftime("%Y-%m-%d")  %></span>
  <!-- <span class="info">阅读<%= @topic.reading_count  %>次</span> -->
  <span class="split"></span>
  <% get_tags(@topic.tags).each do |topic_tag| %>
    <span class="tags"><%= topic_tag %></span>
  <% end %>
</div>
<div id="blog-content" data-content="<%= @topic.body %>">
</div>
<textarea type="text" value="" name="" id="copy" style="opacity:0;position:absolute;"/>
<!-- <div id="disqus_thread"></div> -->
<!-- <script> -->
<!-- (function() { // DON'T EDIT BELOW THIS LINE -->
<!-- var d = document, s = d.createElement('script'); -->
<!-- s.src = 'https://dccmm&#45;world.disqus.com/embed.js'; -->
<!-- s.setAttribute('data&#45;timestamp', +new Date()); -->
<!-- (d.head || d.body).appendChild(s); -->
<!-- })(); -->
<!-- </script> -->
<!-- <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript> -->
<!--                              -->